sudo: required
services:
  - docker

before_instal:
  - docker build -t tfadams/fib -f ./client/Dockerfile.dev ./client

script:
  - docker run tfadams/fib npm test -- --coverage

after_success:
  - docker build -t tfadams/fib-client ./client
  - docker build -t tfadams/fib-nginx ./nginx
  - docker build -t tfadams/fib-server ./server
  - docker build -t tfadams/fib-worker ./worker
  # Login to Docker Hello!
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push tfadams/fib-client
  - docker push tfadams/fib-nginx
  - docker push tfadams/fib-server
  - docker push tfadams/fib-worker
