sudo: required
services:
  - docker

before_install:
  - docker build -t tfadams/fib -f ./client/Dockerfile.dev ./client

script:
  - docker run tfadams/fib npm test -- --coverage

after_success:
  - docker build -t tfadams/fib-client ./client
  - docker build -t tfadams/fib-nginx ./nginx
  - docker build -t tfadams/fib-server ./server
  - docker build -t tfadams/fib-worker ./worker
  # Login to Docker Hello!
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push tfadams/fib-client
  - docker push tfadams/fib-nginx
  - docker push tfadams/fib-server
  - docker push tfadams/fib-worker
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "fib-app"
  env: "FibApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-967195537723"
  bucket_path: "fib-app"
  on:
    branch: master
  access_key_id: $aws_devop_access_key
  secret_access_key: $aws_devop_secret_key
